### ISSUE TITLE
neuer addonkey

### ISSUE THREAD

**Issue by IngoWinter** [FriendsOfREDAXO/uploader#1]
@schuer tob dich aus :)

**Comment by schuer** [comment]
Mein Favorit wäre `uploader`. Und falls schon belegt, `file-upload` als Alternative.

**Comment by staabm** [comment]
da wir 2 uploader haben finde ich den spezifischen namen ganz gut, weil man dann besser sieht was der unterschied ist.

2 allg. namen die die 2 addons nicht unterscheidbar machen wären unpassend IMO

**Comment by schuer** [comment]
@staabm Meinst du mit spezifischem Namen den aktuellen `jquery-file-upload`? Ich finde das jquery darin etwas unnötig, weil sich aus meiner Sicht die Entwickelnden gar nicht damit beschäftigen sollten, dass das Ding auf jQuery basiert. Im JS-Kontext wäre das vielleicht relevant, wenn man technisch dran anknüpfen wollte, aber im REDAXO-/PHP-Kontext finde ich es irrelevant und irgendwie auch keinen schönen AddOn-Key ;)

**Comment by skerbis** [comment]
loadup
filedropper

**Comment by schuer** [comment]
`batch-upload`
`bulk-upload`
`upload-resizer` <-- !
`upload-to-fit`

**Comment by staabm** [comment]
Ich finde es unwichtig dass jquery im namen vorkommt.

Allerdings finde ich gut wenn man z.b. Am namen erkennt das cloenseitiges resizing passiert

**Comment by skerbis** [comment]
load-n-size

**Comment by schuer** [comment]
Ich bin wieder am Anfang: `uploader`. Ihr so?

**Comment by schuer** [comment]
Noch ein paar Meinungen, damit wir loslegen können?
(@alexplusde etwa, der immer gerne aktiv ist bei solchen Themen. @IngoWinter und @Hirbod, die jeweils die Uploader betreuen. @dergel @gharlan @tbaddade vom Core-Team. Alle anderen, die hier mitlesen.)

**Comment by alexplusde** [comment]
mediapool_multiupload

Hätte ich als sinnvoll erachtet, weil es eingrenzt, wo dieser Multiuploadre wirkt.

**Comment by skerbis** [comment]
upload-resizer legt das AddOn auf eine Funktion fest, das stimmt nicht. Nennt es uploader, massload oder sonst wie .

**Comment by IngoWinter** [comment]
Mir ists echt egal...

**Comment by schuer** [comment]
Dann entscheide ich jetzt für `uploader`.

**Comment by schuer** [comment]
Anpassungen im Repo vorgenommen.
