### ISSUE TITLE
svgs lassen sich nicht hochladen

### ISSUE THREAD

**Issue by alexplusde** [FriendsOfREDAXO/uploader#13]
Fehlermeldung: Unzulässiger Dateityp

/cc @pixelpaul @pixeldaniel

**Comment by IngoWinter** [comment]
magste das hier https://github.com/FriendsOfREDAXO/uploader/blob/master/boot.php#L3 einsetzen (den array erweitern, der aktuell nur 'mp4' beinhaltet). danach auch gerne release/ installer aktualisieren :)

**Comment by IngoWinter** [comment]
sowas zu 100% nicht kontroverses ruhig immer direkt reinpinnen...
