### ISSUE TITLE
v.1.1.2 SVG-Error-Bild

### ISSUE THREAD

**Issue by skerbis** [FriendsOfREDAXO/uploader#15]
Etwas unschön: 
<img width="618" alt="bildschirmfoto 2017-10-11 um 21 48 15" src="https://user-images.githubusercontent.com/791247/31462776-155b293c-aece-11e7-9481-29cf92347624.png">

**Comment by IngoWinter** [comment]
https://github.com/FriendsOfREDAXO/uploader/commit/842e86e99823d9b8a157a97f0f23ec719ab9f041

**Comment by skerbis** [comment]
1.2.3: Ok, SVG wird jetzt angezeigt, nur etwas seltsam, evtl. per CSS korrigierbar? max-width?
<img width="487" alt="bildschirmfoto 2017-10-11 um 23 42 44" src="https://user-images.githubusercontent.com/791247/31468409-f719c874-aedd-11e7-8fd6-0840e7da58f8.png">

**Comment by IngoWinter** [comment]
Boah. Ja, CSS. Hab seit Ewigkeiten ein eigenes Backend-Stylesheet mit 
```
img {
    max-width: 100%;
    height: auto;
}
```
drinstehen. Wieso das nicht im Backend Theme drinsteht ist mir schleierhaft.

**Comment by skerbis** [comment]
Ja, das wurde extrem lange diskutiert, wollte es einfügen, aber der Core war dagegen.

**Comment by IngoWinter** [comment]
ohne worte... https://github.com/FriendsOfREDAXO/uploader/commit/9da5ab0f8d125d9fca76c479ed976b04993e4082
