### ISSUE TITLE
Error, uploader.js

### ISSUE THREAD

**Issue by martinm79** [FriendsOfREDAXO/uploader#19]
Dadurch kann man das Addon leider nur benutzen, wenn Redaxo nicht in einem Unterverzeichnis liegt. 
`url: '/redaxo/index.php',`
in:
`\redaxo\src\addons\uploader\assets\uploader.js`

Gerade wenn man local arbeitet, liegt ein Projekt oft in einem Unterverzeichnis.

**Comment by IngoWinter** [comment]
Mach gerne einen PR dazu fertig :)
