### ISSUE TITLE
Parameter im Backend konfigurierbar machen

### ISSUE THREAD

**Issue by schuer** [FriendsOfREDAXO/uploader#2]
Vieles hängt aktuell hard-coded im JS. Wäre prima, wenn wir das im REDAXO-Backend konfigurierbar machen könnten.

Sollte uns das zuviel Aufwand sein, fände ich es auch okay, solche Features dem anderen AddOn `multiupload` zu überlassen, während dieses AddOn hier nur Basisfunktionalität mitbringt.

**Comment by IngoWinter** [comment]
Gehts dir um https://github.com/FriendsOfREDAXO/uploader/blob/master/assets/uploader.js#L43-L58?
 Wenn einer die Einstellungsseite fürs Backend baut, schmuggel ich das gerne ins JS :)
@skerbis hat nicht vielleicht euer Praktikant Lust?

**Comment by skerbis** [comment]
@IngoWinter da werden wir erstmal passen. Es stehen andere Projekte erstmal an. Sorry

**Comment by IngoWinter** [comment]
Hehe, war einen Versuch wert :)

**Comment by schuer** [comment]
Genau, um die vielen Parameter geht’s mir, vor allem imageMaxWidth und imageMaxHeight, denn die hängen in der Praxis oftmals ein bisschen von der Website ab, für die das AddOn im Einsatz ist. Wäre schön, wenn man das im Backend justieren könnte.

Ich kann gerne irgendwann die Einstellungsseite übernehmen, wenn es bis dahin noch niemand gemacht hat. Aber jetzt habe ich erstmal nur noch wenig Zeit für REDAXO-Themen. Wäre also cool, wenn sich jemand das Thema schnappte. (Dafür sind wir ja FOR.)
