### ISSUE TITLE
Probleme mit "mediapool_exif"-Addon

### ISSUE THREAD

**Issue by muenzberg-me** [FriendsOfREDAXO/uploader#20]
Wenn man über den Uploader ein oder mehrere Bilder hochläd, werden leider keine Exif-Daten mit dem mediapool_exif ausgelesen.

**Comment by IngoWinter** [comment]
Werden die Dateien vom Uploader verkleinert?

**Comment by muenzberg-me** [comment]
Ich nehme den Hacken explizit raus

**Comment by IngoWinter** [comment]
Es liegt nicht am Uploader. Exif, IPTC und Metainfos bleiben komplett erhalten. Du kannst das nachvollziehen, indem du ein per Uploader hochgeladenes Bild wieder runterlädst und Exif etc. mit dem Original vergleichst.
Ich habe mir testweise auch das mediapool_exif Addon installiert, es wurden nach Upload Metadaten des Bildes in die Datei Metainfos übernommen.
