### ISSUE TITLE
upload_max_filesize umgehen

### ISSUE THREAD

**Issue by VIEWSION** [FriendsOfREDAXO/uploader#22]
Hallo,
ich habe bei meinem Server eine Beschränkung der Upload-Größe... soweit ist es logisch dass zu große Dateien hier nicht funktionieren... ist auch beim normalen Upload im Medienpool so. Allerdings schein das andere AddOn https://github.com/FriendsOfREDAXO/multiupload keine Probleme damit zu haben. Auch riesige Dateien werden trotz Beschränkung hier hochgeladen. Leider gibt es da aber keine Möglichkeit der automatischen Verkleinerung. Irgendwie muss es also funktionieren das upload_max_filesize zu umgehen... wäre super wenn das mit dem AddOn auch so wäre. Denn der eigentliche Vorteil ist ja dass gerade zu große Bilder anschließend wieder verkleinert werden.

**Comment by IngoWinter** [comment]
Wie ist denn die Größenbeschränkung bei deinem Servver?

**Comment by VIEWSION** [comment]
5MB... is geht ja nicht um den speziellen Server sondern ganz generell... Viele Shared Hoster haben da ein festes Limit... und irgendwie scheint es trotzdem möglich zu sein das zu umgehen... wie gesagt - beim multiupload AddOn geht es. Ich denke das Zauberwort hier dürfte "Chunked Uploads" sein. Normalerweise wird das von jQuery-File-Upload unterstützt: https://github.com/blueimp/jQuery-File-Upload/wiki/Chunked-file-uploads ... ist das ausgeschaltet?

**Comment by IngoWinter** [comment]
Das greift ab 10MB...

**Comment by IngoWinter** [comment]
Probier mal die Zeile hier anzupassen: https://github.com/FriendsOfREDAXO/uploader/blob/master/assets/uploader.js#L53

**Comment by VIEWSION** [comment]
OK... das geht. Das sollte man aber entweder einstellbar machen, oder besser gleich die Server-Limits auslesen und übernehmen.
ABER... Die (über)großen Dateien werden jetzt zwar hochgeladen, nur leider nicht mehr runtergerechnet. Das geht anscheinend nur bei Bildern die in einem Stück hochgeladen werden.

**Comment by IngoWinter** [comment]
PR ist immer gerne genommen ;)

**Comment by VIEWSION** [comment]
OK - mal sehen... ich mache mal ein neues Issue https://github.com/FriendsOfREDAXO/uploader/issues/23 auf - denn dass große Bilder (über Chunksize) nicht heruntergerechnet werden, hat mit dem ursprünglichen Issue ja nichts zu tun...
