### ISSUE TITLE
Sehr große Bilder werden nicht heruntergerechnet

### ISSUE THREAD

**Issue by VIEWSION** [FriendsOfREDAXO/uploader#23]
Wenn recht große Bilder hochgeladen werden (chunked uploads), dann bleiben die Bilder unverändert in Originalgröße

**Comment by IngoWinter** [comment]
Was hast du bei den Uploader Settings eingestellt? Kannst du mal "max Dateigröße" auf 500 und die beiden Kantenlängenwerte auf 1000 setzen und gucken obs dann läuft mit dem resize?

**Comment by VIEWSION** [comment]
Ok - das geht... dann läuft was mit "Maximale Dateigröße" schief, oder versteh ich das nicht? Denn wenn ich da 2MB eigestellt habe, müsste es doch erst recht neu rechnen wenn Bilder z.B. 15MB groß sind ,oder? Der Vergleich der Dateigröße müsste doch genau umgekehrt sein... also Bilder > 2MB neu berechnen und < 2MB ignorieren.

**Comment by IngoWinter** [comment]
Ich hab da eben schon ein Issue zu aufgemacht: 
https://github.com/FriendsOfREDAXO/uploader/issues/24

**Comment by IngoWinter** [comment]
Es gibt eine neue Version im Installer, das Limit für chunked uploads ist auf 5mb runtergesetzt und die irreführende Einstellung unter Settings entfernt
