### ISSUE TITLE
"Maximale Dateigröße" unter Settings irreführend

### ISSUE THREAD

**Issue by IngoWinter** [FriendsOfREDAXO/uploader#24]
Was dort eingestellt wird, ist die max Größe, bis zu der Bilder vom Skript verarbeitet/ resized werden. Imho hat dieser Wert nur einen Sinn, nämlich den bildverarbeitenden Browser vorm Explodieren zu bewahren, falls jemand ein 500MB Bild hochlädt.
Ich würde die Einstellungsmöglichkeit komplett entfernen und statddessen einen fixen Wert von 30 MB hinterlegen.

**Comment by IngoWinter** [comment]
@schuer solle ma so machen?

**Comment by schuer** [comment]
Von mir aus jederzeit gerne ausdünnen und vereinfachen! 👍 
Aber hey, du bist Lead @IngoWinter :)

**Comment by IngoWinter** [comment]
https://github.com/FriendsOfREDAXO/uploader/releases/tag/v1.1.5
