### ISSUE TITLE
Bei REDAXO Installation in Unterordner funktioniert der Upload nicht

### ISSUE THREAD

**Issue by wexstorm** [FriendsOfREDAXO/uploader#26]
Leider funktionieren die Relativen Pfade in 3 Dateien nicht mit Installationen (oder Testsystemen), die in Unterordnern liegen.
Datei package.yml
Zeile 21:
endpoint: '/redaxo/index.php?page=uploader/endpoint'
=>
endpoint: 'index.php?page=uploader/endpoint'

Datei ouploader_iw_upload_handler
Zeile 160:
$v->thumbnailUrl = '/redaxo/index.php?rex_media_type=rex_mediapool_preview&rex_media_file=' . $v->name;
=>
$v->thumbnailUrl = 'index.php?rex_media_type=rex_mediapool_preview&rex_media_file=' . $v->name;

Datei uploader.js (in beiden assets Ordnern nach Installation)
Zeile 95:
url: '/redaxo/index.php',
=>
url: 'index.php',

Ansonsten natürlich ein wirklich sehr gelungenes AddOn, danke dafür!

**Comment by skerbis** [comment]
Kann ich bestätigen

**Comment by skerbis** [comment]
https://github.com/FriendsOfREDAXO/uploader/pulls
