### ISSUE TITLE
Uploader-Felder verschwinden nach PJAX-(Re)load

### ISSUE THREAD

**Issue by elpschulzo** [FriendsOfREDAXO/uploader#31]
Kleinigkeit aber sollte vielleicht erwähnt werden...

Wenn man im MP auf "Medium hinzufügen" klickt, erscheint der Upload-Dialog des Uploader-AddOns. Klickt man dann noch einmal auf den selben Menüpunkt/Tab ("Medium hinzufügen") wird dessen Content offenbar per AJAX/PJAX neu geladen und eingefügt. Dann bleiben auch die Uploader-Schaltflächen weg und der normale Upload-Button erscheint.

**Comment by IngoWinter** [comment]
Der Upload Dialog wird per Javascript erstellt, dabei werden Teile des originalen HTML ersetzt/ gelöscht, die beim pjax Reload nicht erneuert werden. Deswegen verhindert das uploader Skript nun den Reload per pjax, es wird bei Klick auf "Medium hinzufügen" oldschool komplett neu geladen.

**Comment by elpschulzo** [comment]
Is einfach und funktioniert. Passt.

**Comment by elpschulzo** [comment]
Eig. klar das es klappen muss, habs eben trotzdem nochmal getestet. Läuft. Danke @IngoWinter!

**Comment by IngoWinter** [comment]
aber gerne :)
