### ISSUE TITLE
Upload - ab welcher Größe werden die Medien verkleinert

### ISSUE THREAD

**Issue by tbaddade** [FriendsOfREDAXO/uploader#35]
Aktuell steht die Info

> übergroße Bilder vor Upload verkleinern

Ich denke es wäre hilfreich auch die definierten px mit auszugeben

> Bilder die größer als 4.000 x 4.000px sind vor Upload verkleinern

**Comment by IngoWinter** [comment]
pr welcome :)

**Comment by tbaddade** [comment]
Ich schließe wegen Inaktivität.
