### ISSUE TITLE
Wunsch :: Verkleinerung bitte nur bei Pixel-Formaten

### ISSUE THREAD

**Issue by skerbis** [FriendsOfREDAXO/uploader#36]
Aktuell werden SVGs bei aktivierter Verkleinerung in PNGs umgewandelt.

**Comment by IngoWinter** [comment]
check mal bitte ob das hier hilft: https://github.com/FriendsOfREDAXO/uploader/pull/37

**Comment by skerbis** [comment]
Alle 3 sind svg, aber nur das dritte in diesem Fall wird nicht angefasst
seltsam ..
![bildschirmfoto 2018-08-15 um 15 07 56](https://user-images.githubusercontent.com/791247/44149631-1697633a-a09d-11e8-98d2-f474d04ba039.png)

**Comment by skerbis** [comment]
ist irgendein Safari bug … scheint so

**Comment by ynamite** [comment]
Ich hab momentan dasselbe Phänomen. Wenn ich ein SVG hochlade und dabei die Checkbox für die Bilderverkleinerung aktiviert habe, wird's in ein PNG umgewandelt. 
Cache löschen in Redaxo/Browser bringt nix.

Firefox 66.0.3

**Comment by skerbis** [comment]
Das Problem ist leider noch da.

**Comment by IngoWinter** [comment]
Ich kann das Problem noch immer nicht nachvollziehen - bei mir macht er das nicht. Ich vermute, dass das irgendwas OS/Browserspezifisches ist. Leider finde ich auch nix per Suchmaschine dazu. Deshalb wird da von mir nix kommen ¯\_(ツ)_/¯

**Comment by skerbis** [comment]
Vielleicht liegt es ja am Vendor und dieser müsste nur ausgetauscht werden? Gibt es eine neuere Version?

**Comment by IngoWinter** [comment]
da die vendo version nun topaktuell ist mach ich nochmal zu :)
