### ISSUE TITLE
Dateitypen

### ISSUE THREAD

**Issue by olien** [FriendsOfREDAXO/uploader#4]
Mehr Dateitypen zulassen oder den Weg über den "normalen" Upload (Medium hinzufügen) zulassen.
Aktuell ist es nich möglich z.B. eine mp4 Datei hochzuladen ohne das Addon zu deaktivieren.

LG
Oliver

**Comment by IngoWinter** [comment]
Magst du dafür einen PR bei Redaxo machen, analog zu https://github.com/redaxo/redaxo/pull/1214?

**Comment by IngoWinter** [comment]
Ich habe mp4 an der passenden Stelle eingesetzt: https://github.com/FriendsOfREDAXO/uploader/commit/a52234b5e3a73d2b24c27e6ae4f10cde6ef3f16c
Man könnte das sicherlich auch per Eingabefeld im Backend lösen, ist mir aber ehrlichgesagt zu viel Aufriss.

**Comment by alexplusde** [comment]
Müsste man das nicht hier anpassen?
https://github.com/redaxo/redaxo/blob/3b11035f966eb92affc4134e77b9f8c5a877a344/redaxo/src/addons/mediapool/package.yml#L20-L22

**Comment by IngoWinter** [comment]
ja, müsste man. aber die pr-zyklen im uploader sind kürzer :)

**Comment by alexplusde** [comment]
@IngoWinter ich verstehe nicht, warum der reguläre Redaxo-Uploader die Dateien frisst, das Verhalten ist ja dann inkonsistent

**Comment by IngoWinter** [comment]
@alexplusde der Core verwendet eine Blacklist ([blocked_extensions](https://github.com/redaxo/redaxo/blob/master/redaxo/src/addons/mediapool/package.yml#L20)) beim Upload - alles was nicht auf der Blacklist steht, kann hochgeladen werden. Das Multiupload Skript in `uploader` nutzt aber eine Whitelist - nur das was auf der Whitelist steht, kann hochgeladen werden. Als ich das Addon gemacht habe, bin ich auf den irreführenden key [allowed_doctypes](https://github.com/redaxo/redaxo/blob/master/redaxo/src/addons/mediapool/package.yml#L21) reingefallen, eigentlich müsste der key "has_mime_icon" heissen, die Werte werden [nur hier](https://github.com/redaxo/redaxo/blob/85962ea18d66c8c330f41f9fd6bfb2c0cb1a09d7/redaxo/src/addons/mediapool/pages/media.php#L647) verwendet.

Imho wäre es sinnvoll, eine vom Core unabhängige und durch den Admin einstellbare Whitelist zu haben. Sprich wir geben bei der Installation ein Basis-Whitelist vor, die im Backend auf der Settingspage vom Admin editiert/ erweitert werden kann. @olien @skerbis @schuer Meinungen?

**Comment by schuer** [comment]
Ich habe dazu leider keine Meinung. Nur eine Tendenz dahin, Settings und Menüpunkte in REDAXO so schlicht wie möglich zu halten. Ich würde dementsprechend so frei wie möglich mit der Definition bleiben, welche Dateitypen hochgeladen werden können. Von mir aus sogar `*`.

**Comment by IngoWinter** [comment]
Ok, dann ists vielleicht am einfachsten das analog zum Core zu machen. Sprich alles zum Upload zuzulassen und nach dem Upload bestimmte Dateitypen umzubenennen. Muss ich vermutlich [hier](https://github.com/FriendsOfREDAXO/uploader/blob/master/lib/uploader_iw_upload_handler.php#L89) reinsetzen.

**Comment by IngoWinter** [comment]
@olien @alexplusde mögt ihr https://github.com/FriendsOfREDAXO/uploader/releases/tag/v1.1.2 einmal testen? Wenns läuft schiebe ichs in den Installer...

**Comment by alexplusde** [comment]
Hat meines Wissens funktioniert.

**Comment by IngoWinter** [comment]
du, wenn microsoft und apple ihre software von den endusern testen lassen, könne wir das erst recht 👍
