### ISSUE TITLE
Dateinamen vor dem Upload anpassen

### ISSUE THREAD

**Issue by tbaddade** [FriendsOfREDAXO/uploader#41]
https://github.com/redaxo/redaxo/issues/1458

**Comment by IngoWinter** [comment]
Wie soll denn das aussehen? Im verlinkten Issue gehts um zu aktualisierende Dateien, nicht um neue - wie hängt das zusammen?

**Comment by tbaddade** [comment]
Es geht um die Umbenennung von Dateinamen nicht die Dateien.

Aktuell würde ich mir ein Textfeld im Uploader wünschen, der den aktuellen Dateinamen aus dem Dropfile dort reinholt (am besten sogar den voraussichtlichen gesyncten Namen) und der User diesen ggf. anpassen kann.

Problem ist momentan, dass ein Dateiname wie "Der-Oktopus.jpg" auf nicht Linuxsysteme umgewandelt wird in `der-oktopus_1.jpg` siehe hier das Issue https://github.com/redaxo/redaxo/issues/1586

**Comment by tbaddade** [comment]
Ich schließe wegen Inaktivität.
