### ISSUE TITLE
Rechte nicht anpassbar

### ISSUE THREAD

**Issue by VIEWSION** [FriendsOfREDAXO/uploader#44]
Kann es sein dass man dafür keine Recht braucht bzw. keine Rechte anpassbar sind? Wenn ich einen User / eine Rolle ohne Rechte anlege, kann dieser User eigentlich nur sein Profil aktualisieren..... und er hat Zugriff auf den Uploader. Das sollte nicht so sein, oder?

**Comment by IngoWinter** [comment]
Mach gerne einen PR wenn du das brauchst :)

**Comment by skerbis** [comment]
Ich mache das. Habe gerade das gleiche Problem.

**Comment by skerbis** [comment]
Bitte aktuelle GitHub-Version testen @VIEWSION - ich war mal so frei

**Comment by skerbis** [comment]
Uploader kann jetzt komplett deaktiviert werden je Nutzer. Die Anzeige der Seite im Menü kann auch gesteuert werden.

**Comment by VIEWSION** [comment]
@skerbis Vielen Dank! Habs kurz getestet... scheint problemlos zu laufen.

**Comment by skerbis** [comment]
@IngoWinter ? Release?

**Comment by skerbis** [comment]
Ja aufgrund der Rechte.
