### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by paddle07** [FriendsOfREDAXO/uploader#46]
Hi, seit ich die Version 2.0. bei verschiedenen Installation installiert habe kommten bei Kunden folgende Error: JSON Parse error: Unrecognized token ‘<’ oder JSON.parse: unexpected charachter ... bei mir sieht's gut aus...

**Comment by paddle07** [comment]
Liegt an der Rollen-Berechtigung... wenn unter Allgemein nur «Uploader» ohne «Uploader Seite anzeigen» drin ist, kommt die Fehlermeldung.

**Comment by skerbis** [comment]
@paddle07 wo genau kommt der Fehler?
Ich kann es nicht reproduzieren.

**Comment by paddle07** [comment]
siehe nachträglicher Comment ... sobald ich unter Benutzer eine Rolle anlege und unter Allgemein nur «Uploader» ohne «Uploader Seite anzeigen» freischalte, kommt der Error beim Upload. «SyntaxError: JSON Parse error: Unrecognized token '<'» ist die komplette Error-Meldung, die im Medienpool nach Klick auf «Upload starten» unterhalb Bildname erscheint. Auf verschiedenen Browsern und Installationen getestet.

**Comment by IngoWinter** [comment]
https://github.com/FriendsOfREDAXO/uploader/blob/master/package.yml#L16
https://github.com/FriendsOfREDAXO/uploader/blob/master/pages/endpoint.php

**Comment by IngoWinter** [comment]
@paddle07 bug bestätigt. skerbis hat schon eine gute idee zur lösung

**Comment by skerbis** [comment]
@paddle07 @IngoWinter  bitte aktuelle GitHub-Version kurz testen und mir kurz bescheid geben.

**Comment by paddle07** [comment]
@skerbis @IngoWinter Bei mir sieht's gut aus

**Comment by skerbis** [comment]
ok … ich release

**Comment by IngoWinter** [comment]
"bei mir auch" wollte ich grad schreiben aber da war es schon released ^^
