### ISSUE TITLE
Problem mit nicht erlauten Dateitypen

### ISSUE THREAD

**Issue by ynamite** [FriendsOfREDAXO/uploader#48]
Obwohl nur JPGs zugelassen sind mit `REX_MEDIA[id=1 widget=1 types=jpg]` lädt der Uploader andere Formate trotzdem hoch (zum Beispiel eine PNG Datei).

Wenn man danach "Datei übernehmen" klickt, wird die Datei ins Rex-Media Widget übernommen und der Datensatz kann gespeichert werden. Mit den Default-Einzel-Uploader geht das nicht.

Redaxo 5.6.5
Uploader 2.0.1

**Comment by ynamite** [comment]
https://github.com/FriendsOfREDAXO/uploader/pull/49

**Comment by IngoWinter** [comment]
Ist im Installer, thnx
