### ISSUE TITLE
Redakteur sieht Uploader nicht mehr

### ISSUE THREAD

**Issue by alexplusde** [FriendsOfREDAXO/uploader#53]
In REDAXO 5.7 ist der Uploader im Medienpool für Redakteure (nicht-Admins) verschwunden. Ein separates Recht dazu konnte ich nicht entdecken.

**Comment by skerbis** [comment]
<img width="1165" alt="Bildschirmfoto 2019-03-17 um 21 49 33" src="https://user-images.githubusercontent.com/791247/54497775-f02ec200-48fe-11e9-949a-cc7c066cece8.png">

**Comment by alexplusde** [comment]
Wieso ist das so komisch sortiert?

**Comment by skerbis** [comment]
Keine Ahnung

**Comment by skerbis** [comment]
close @alexplusde ?

**Comment by alexplusde** [comment]
Ne, es wäre die Frage, warum vor einem Update noch alles in Ordnung war und das Recht nicht hätte übernommen werden sollen.

**Comment by skerbis** [comment]
Eine Info dazu stand im Update

**Comment by skerbis** [comment]
Update: die Info stand in der offline genommenen 2.0 ... ich habe den Hinweis jetzt wieder eingepflegt.

**Comment by alexplusde** [comment]
Dann wird es so gewesen sein. Kann man nicht das Recht beim Update von 1 auf 2 initial setzen? So, wie man es gewohnt war?

(Wenn die Antwort „PR welcome“ lautet kann man es gleich schließen ;))

**Comment by skerbis** [comment]
Ja kann man. Aber die 2.0.x ist jetzt auch wieder so lange online, dass sich der Aufwand evtl. Nicht lohnt. Daher close erstmal.
