### ISSUE TITLE
Unzulässigen Dateityp

### ISSUE THREAD

**Issue by skerbis** [FriendsOfREDAXO/uploader#54]
,obwohl im Widget keine zulässigen Dateitypen festgelegt wurden. 

Wurden welche festgelegt, funktioniert der Upload. 

REDAXO 5.7
Betroffene Versionen: 2.0.2 - 2.0.3

**Comment by ynamite** [comment]
Die Änderung war von mir. Hatte mit und ohne festgelegte Dateitypen getestet.

Darf ich fragen welchen Browser du verwendest?

**Comment by skerbis** [comment]
Safari 12

**Comment by ynamite** [comment]
Hoppla, du hast recht, fix ist in folgendem Patch drin. Kannst du mal testen?
https://github.com/FriendsOfREDAXO/uploader/pull/55

**Comment by skerbis** [comment]
Super! Danke @ynamite
