### ISSUE TITLE
Aufruf der Hilfe wirft rex_exception (whoops)

### ISSUE THREAD

**Issue by darwin26** [FriendsOfREDAXO/uploader#56]
` rex_exception    

The headline structure in the given markdown document is malformed, it starts with a h3 instead of a h2.`

**rex_exception:** The headline structure in the given markdown document is malformed, it starts with a h3 instead of a h2.
**File:** redaxo/src/core/lib/util/markdown.php
**Line:** 76

**Comment by IngoWinter** [comment]
ist korrigiert
