### ISSUE TITLE
Imagick + Mittwald + PHP FPM = :(

### ISSUE THREAD

**Issue by anveno** [FriendsOfREDAXO/uploader#57]
Sehr speziell, aber vielleicht hat ja mal jemand den gleichen Fehler...

Bei Mittwald kommt es mit PHP FPM zu einer Fehlermeldung, da imagick nicht verfügbar ist.
Der Upload erfolgt trotzdem.

Fehler in der Log:
> ImagickException | NoDecodeDelegateForThisImageFormat `PNG' @ error/constitute.c/ReadImage/501 | redaxo/src/addons/uploader/lib/uploader_upload_handler.php 

"Es könnte sein dass imagick modul installiert ist, dieses aber unter fpm die binary nicht nutzen kann"

**Temporäre Lösungsmöglichkeit:**
In der lib\uploader_upload_handler.php gibt es die Einstellungsmöglichkeit 'image_library'.
0 =  GD, 1 = imagick (mit Fallback auf GD), 2 = ImageMagick.
In der pages\endpoint.php könnte man also 'image_library' => 0 hinzufügen und die Fehlermeldung verschwindet.

**Comment by IngoWinter** [comment]
Ist in die Readme aufgenommen
