### ISSUE TITLE
Notice: Trying to access array offset on value of type null

### ISSUE THREAD

**Issue by omphteliba** [FriendsOfREDAXO/uploader#58]
Ich bekomme seit Redaxo 5.10 folgende Notice im System Log:

Trying to access array offset on value of type null 
Datei: redaxo/src/addons/uploader/lib/uploader_upload_handler.php
Zeile: 471

Redaxo 5.10.0
PHP 7.4.3

**Comment by IngoWinter** [comment]
Ist wohl ne php 7.4 geschichte. Danke fürs Bescheid sagen.

**Comment by IngoWinter** [comment]
mit vendor update in 2.1.0 gefixt
