### ISSUE TITLE
Probleme mit MEDIA_ADDED und MEDIA_UPDATED (aufgefallen via mediapool_exif)

### ISSUE THREAD

**Issue by olien** [FriendsOfREDAXO/uploader#60]
https://github.com/FriendsOfREDAXO/mediapool_exif/issues/18

**Comment by akrys** [comment]
Das ist kein Problem mit medapool_exif selbst. Es liegt daran, dass in uploader_iw_upload_handler::handle_file_upload mit dem Aufruf uploader_meta::save($success); alle Metadaten, die vorher via MEDIA_ADDED und MEDIA_UPDATED ermittelt und gespeichert wurden überschrieben werden.

Wahrscheinlich müsste uploader die Speicherung der Meta-Daten selbst in MEDIA_ADDED und MEDIA_UPDATED auslagern, so dass die Updatekette eingehalten werden kann. Wenn im Nachhinein alles überschrieben wird, hat _kein_ Addon die Möglichkeit, Meta-Daten beim Upload selbst zu ermitteln. Das müsste dann _immer_ im Nachhinein passieren.

**Comment by olien** [comment]
danke für die info. vielleicht kann das ja geändert werden...

**Comment by akrys** [comment]
Ist hier schon mal was geändert worden?

Habe aufgrund https://github.com/FriendsOfREDAXO/mediapool_exif/issues/28 in einem aktuellen Testlauf mit Redaxo 5.15.1 und Uploader 2.4.1 gemacht. Dort wurden die EXIF-Daten ohne Probleme einfach eingelesen.

**Comment by akrys** [comment]
Lösungsvorschlag sieht nun wie folgt aus:

Im `metainfo`-Addon wird ein Flag-Parameter an die Funktion `fetchRequestValues`, das leere Werte ignoriert werden dürfen:
https://github.com/redaxo/redaxo/pull/5852

Uploader ruft diese Funktion mit dem Wert `false` auf, um das Überschreiben zu verhindern:
https://github.com/FriendsOfREDAXO/uploader/pull/78

**Comment by eaCe** [comment]
Es gibt einen kleinen Workaround hierfür, gerne testen.

**Comment by alxndr-w** [comment]
closed in https://github.com/FriendsOfREDAXO/uploader/pull/78
