### ISSUE TITLE
Rotate image when exif orientation is set

### ISSUE THREAD

**Issue by Daimonion1980** [FriendsOfREDAXO/uploader#63]
Hallo Leute. 

Ich schreibe einfach mal auf Deutsch, da ich das Problem dann besser beschreiben kann. 

Ich habe in 2017 das Problem unter Redaxo 4 gehabt, dass die Bildorientierung bei einigen Bildern nicht korrekt war:

https://www.redaxo.org/forum/allgemeines-r4-f27/medienpool-zeigt-die-bilder-in-der-falschen-ausric-t21978.html

Dieses Problem habe ich nun auch. Die Bilder werden beim Upload nicht richtig orientiert. In den Metadaten steht die Orientation aber drin. 

Leider funktioniert der Codesnippet aus dem Link leider nicht, wenn das Uploader AddOn aktiv ist. (Ohne gehts, dass habe ich getestet)

In der Tat wäre es aber cool, wenn das UploaderAddon dieses Codesnippet bzw. die Funktion der Orientierung des Bildes implementieren würde und selbst schon die Bilder drehen würde. 

Wo könnte man denn das im Uploader Addon unterbringen? Ggfs. gibts ja auch clientseitig eine gute Stelle wo man die Orientierung unterbringen kann. 

Edit: Nun ist mir klar warum das Codesnippet nicht mit Uploader funktioniert. Er kopiert die Metadaten nicht mit in das neue Bild. Es wäre sicher für Uploader ein einfaches das Bild vor der Kopieraktion (die für das Resizing gemacht wird.) das Bild korrekt zu drehen.

**Comment by IngoWinter** [comment]
uploader entfernt keine exifs und dreht auch keine bilder. ich schlage vor, du schreibst dir einen effekt für den media manager, der bei bedarf das bild dreht.
