### ISSUE TITLE
Probleme mit Content-Security-Policy

### ISSUE THREAD

**Issue by alxndr-w** [FriendsOfREDAXO/uploader#67]
Der Uploader benötigt `script-src 'unsafe-eval'` als CSP-Header, um ordnungsgemäß zu funktionieren.

**Comment by eaCe** [comment]
Das lässt sich wohl nicht vermeiden

**Comment by eaCe** [comment]
@alxndr-w ist das wirklich noch so?

**Comment by alxndr-w** [comment]
Ich wüsste nicht, dass JS schon in eigene Dateien ausgelagert wurden.

**Comment by eaCe** [comment]
Eval kam doch von jQuery. Kann kein weiteres finden. Oder ist unsafe inline gemeint?

**Comment by alxndr-w** [comment]
Ah stimmt, ich habe das nicht aufmerksam gelesen. Aber ganz ehrlich: das ist 2 Jahre her. Müsste ich jetzt auch extra erstmal überprüfen. Ich hatte es dann im Projekt erlaubt.

**Comment by eaCe** [comment]
Bei Inline-Scripts könnten wir eine Nonce hinzufügen, ich hatte es mal getestet, aber die ist bei mir immer leer. Komisch

**Comment by alxndr-w** [comment]
Scheint eh sonst niemanden zu stören.
