### ISSUE TITLE
Übernehmen nach Upload

### ISSUE THREAD

**Issue by skerbis** [FriendsOfREDAXO/uploader#7]
<img width="1175" alt="bildschirmfoto 2017-09-24 um 23 33 01" src="https://user-images.githubusercontent.com/791247/30787052-feae65fa-a180-11e7-945f-9663848f5dba.png">
Mit einfachen Mediafeld kein Problem - funktioniert. 
Kommt man von einer Medialist, wird die Datei nicht übernommen. Auch schließt sich das Fenster sofort.

**Comment by IngoWinter** [comment]
[Sollte gefixt sein](https://github.com/FriendsOfREDAXO/uploader/blob/master/assets/uploader.js#L144-L153), bitte einmal testen.

**Comment by skerbis** [comment]
@IngoWinter perfekt, nicht vergessen Version anpassen
