### ISSUE TITLE
SyntaxError: JSON Parse error: Unrecognized token '<'

### ISSUE THREAD

**Issue by olien** [FriendsOfREDAXO/uploader#70]
![image](https://user-images.githubusercontent.com/330516/137593731-7c88843e-5e41-419e-8993-bcbc696afa2c.png)

Die Bilder werden trotzdem hochgeladen.

<details>
<summary>System report (REDAXO 5.12.1, PHP 7.4.21, MySQL 5.7.34)</summary>

| REDAXO        |            |
| ------------: | :--------- |
|       Version | 5.12.1     |

| PHP           |            |
| ------------: | :--------- |
|       Version | 7.4.21     |
|       OPcache | yes        |
|        Xdebug | no         |

| Database      |              |
| ------------: | :----------- |
|       Version | MySQL 5.7.34 |
| Character set | utf8mb4      |

| Server        |               |
| ------------: | :------------ |
|            OS | Darwin        |
|          SAPI | cgi-fcgi      |
|     Webserver | Apache/2.4.48 |

| Request       |             |
| ------------: | :---------- |
|       Browser | Safari/15.0 |
|      Protocol | HTTP/1.1    |
|         HTTPS | yes         |

| Packages                    |               |
| --------------------------: | :------------ |
|                accessdenied | 1.0.6         |
|                     adminer | 1.9.1         |
|               animatedlogin | 1.0.0         |
|                       awnav | 0.3.1         |
|                      backup | 2.7.1         |
|                 be_password | 2.0.0         |
|                    be_style | 2.12.1        |
|         be_style/customizer | 2.12.0        |
|             be_style/redaxo | 2.12.1        |
|                     bloecks | 3.1.0         |
|            bloecks/cutncopy | 3.1.0         |
|                bootstrapper | 1.0.0-alpha.1 |
|                     cronjob | 2.8.0         |
|                       debug | 1.1.1         |
|                   developer | 3.9.0         |
|                      ffmpeg | 1.0.0         |
|                  focuspoint | 3.0.2         |
|                  httpheader | 1.0           |
|                 insert_text | 1.1.1         |
|                     install | 2.9.1         |
|                    lazyload | 0.1.3         |
|                 maintenance | 2.6.3         |
|                    markitup | 3.6.1         |
|      markitup/documentation | 1.1.0         |
|                      mblock | 3.3.0         |
|               media_manager | 2.11.1        |
|                media_srcset | 2.0.4         |
|                   mediapool | 2.10.1        |
|                    metainfo | 2.8.1         |
|                       mform | 6.0.13        |
|                  mform/docs | 1.1           |
|               minify_images | 2.0.0         |
|               modulsammlung | 4.15.2        |
| modulsammlung/documentation | 1.0           |
|            navigation_array | 1.1.1         |
|                   phpmailer | 2.10.2        |
|                        plyr | 3.11.1        |
|             project_manager | 1.3.5         |
|      project_manager/client | 1.1.0         |
|            quick_navigation | 5.2.0         |
|                   search_it | 6.7.3         |
|      search_it/autocomplete | 6.7.3         |
|     search_it/documentation | 6.7.3         |
|         search_it/plaintext | 6.7.3         |
|             search_it/stats | 6.7.3         |
|                       sprog | 1.2.0         |
|                   structure | 2.12.1        |
|           structure/content | 2.12.0        |
|                       theme | 1.3.3         |
|                    uploader | 2.2.2         |
|                         url | 2.0.0-dev     |
|                       users | 2.8.0         |
|                        ycom | 4.0.6         |
|                   ycom/auth | 4.0.6         |
|                  ycom/group | 4.0.6         |
|                       yform | 4.0.0-beta2   |
|                 yform/email | 4.0.0-beta2   |
|               yform/manager | 4.0.0-beta2   |
|                 yform/tools | 4.0.0-beta2   |
|                    yrewrite | 2.7           |

</details>

**Comment by alxndr-w** [comment]
https://github.com/FriendsOfREDAXO/uploader?tab=readme-ov-file#syntaxerror-jsonparse-unexpected-character-at-line-2-column-1-of-the-json-data
