### ISSUE TITLE
Datei austauschen im Medienpool

### ISSUE THREAD

**Issue by chrisrex** [FriendsOfREDAXO/uploader#72]
Wenn man nachträglich ein Bild nach dem Upload austauschen will, greift das resize beim Uploader nicht mehr. Ich könnte somit wieder z.B. 60MB große Bilder in den Medienpool schleusen.

**Comment by IngoWinter** [comment]
Korrekt. Das Addon ersetzt die Upload nur Seite des Medienpool.

**Comment by chrisrex** [comment]
Bin ich hier an falscher Stelle? Siehe auch:
https://friendsofredaxo.slack.com/archives/C1BAXLN2F/p1638447593421200

**Comment by IngoWinter** [comment]
Bei Fragen zum Uploader bist du hier richtig. Worum geht es denn?

**Comment by IngoWinter** [comment]
Das habe ich bei der Entwicklung nicht implementiert, weil die aktualisieren Funktion imo kaum genutzt wird. Da die letzten Wenn du das zwingend brauchst, mach gerne einen PR.

**Comment by chrisrex** [comment]
Zwingend benötige ich es nicht. Ich muss dann beim Austausch dran denken, dass ich das Bild vorher einfach schon skaliere.
