### ISSUE TITLE
OPTIMIERUNG: Checkbox für "Titel aus Dateiname übernehmen"

### ISSUE THREAD

**Issue by bitshiftersgmbh** [FriendsOfREDAXO/uploader#74]
Ich habe hier gerade so ein Projekt, wo ich Inhalte manuell von alter Seite (mit komischem CMS gemacht) zur neuen R5-Seite umziehe. Dabei muss ich recht viele Bilder anpassen. Weil die meisten davon in Lightboxen oder Slidern auftauchen und Zusatzinfos enthalten, die in diesen UI-Elementen auch angezeigt werden müssen und weil die Bilder aus dem anderen CMS einfach durchnummerierte Dateinahmen sind, hab ich folgendes Problem:

Um noch durchzusehen, nutze ich besagte Zusatzinfo als Dateiname. Ich weiß nicht, ob das in 2023 noch ein SEO-Thema ist, früher aber war es wphl mal so, dass auch Dateinamen eine Rolle spielten. Auf jeden Fall wird dann aus `1231231123.jpg` z.B. `Gerberstraße 2 - Grundrisse - 2-Raum-Wohnung - EG bis 4.OG.jpg`.

Wenn ich nun diese vielen Bilder stapelweise (per Uploader-AddOn) in den Medienpool werfe, hab ich das Thema, dass ich danach nochmal **jedes einzelne Bild extra** öffnen und anpassen muss, um den Titel nochmal neu zu setzen. Hinzu kommt, dass der Medienpool für solche Nacharbeiten ungünstig sortiert ist bzw. keine Sortierung einstellbar ist. Wenn ich in einem MP-Ordner also 50 (noch titellose) Bilder drin hab, muss ich dann für die 2. Hälfte immer ewig scrollen und das nächste Bild in der Reihe finden. Das verdoppelt meinen Gesamtaufwand und ich hab mit dem Bilderprozess nun bestimmt (nur bei diesem Projekt) schon 8h verbraucht, wo es mit einem kleinen Zusatzfeature vielleicht nur 4h hätten sein müssen.

Ich denke, es sollte keinen besonders großen Aufwand machen, unter der Checkbox `"übergroße Bilder vor Upload verkleinern"` noch eine weitere einzufügen mit `"Titel aus Dateiname übernehmen"`. Diese sollte vielleicht standardmäßig nicht angehakt sein, da man ja oben auch selbst einen Titel eingeben kann (was ja dann aber für alle Uploads im Stapel gilt und mein o.g. Problem auch nicht löst).

Ich würde mich mal daran versuchen und in Kürze hier einen PR einreichen. Würde mich freuen, wenn das Anklang findet und aufgenommen wird,

**Comment by bitshiftersgmbh** [comment]
Sieht in deutscher Sprache dann jetzt so aus:

![image](https://user-images.githubusercontent.com/7023022/224680861-3d3df216-5e56-4601-9c93-62349a82982b.png)

Ich war so frei, die fettgedruckten Labels gleich mal auf "normal" zu ändern. Wenn das jemanden stört, gern auch wieder rückgängig machen.

**Comment by eaCe** [comment]
@bitshiftersgmbh das ist doch gemerged? Ich mach hier mal zu. Sollte ich etwas übersehen haben, bitte wieder öffnen
