### ISSUE TITLE
Unexpected token - ungültige Antwort beim Upload

### ISSUE THREAD

**Issue by alexplusde** [FriendsOfREDAXO/uploader#8]
Die Dateien wurden dennoch korrekt hochgeladen und übernommen.

![image](https://user-images.githubusercontent.com/3855487/31011929-5319eb86-a510-11e7-8b9c-b3a70d9ad51f.png)

**Comment by IngoWinter** [comment]
Schwierig zu sagen, was da passiert. Wahrscheinlich bekommt der Uploader statt einer gültigen JSON Response irgendeine PHP Fehlermeldung/ Notice vom Server zurück. Kannst du das irgendwie reproduzieren?

**Comment by alexplusde** [comment]
War auch meine Vermutung.

Ich kanns reproduzieren, im Sinne von: Ich kann dir Zugang zu einem Redaxo geben, bei dem das durchgehend auftritt...

**Comment by skerbis** [comment]
@alexplusde hast du die Laufzeitumgebung hinsichtlich Uploadgrößen, Post-Zeiten etc. überprüft? Evtl. auch mal die PHP-Version gewechselt?

**Comment by IngoWinter** [comment]
Oder steht vielleicht irgendwas im Error Log? Ansonsten könntest du mal im [Upload Handler](https://github.com/FriendsOfREDAXO/uploader/blob/master/lib/uploader_iw_upload_handler.php) wühlen, da gibts 2 relevante Funktionen: `handle_file_upload` und `generate_response`. Zuerst wird die `handle_file_upload` aufgerufen, die die Drecksarbeit erledigt - die Datei validieren, umbenennen und die Metainfos eintragen. Danach funkt die `generate_response` JSON zurück ans Backend.

Du kommst anscheinend mindestens bis [Zeile 108](https://github.com/FriendsOfREDAXO/uploader/blob/master/lib/uploader_iw_upload_handler.php#L108) der `handle_file_upload`, die Datei ist erfolgreich hochgeladen und mit dem MP synchronisiert. Ab hier könntest du gezielt ein paar `error_log(print_r($file, 1));` einstreuen, um mal zu gucken, wo es schief läuft. Wenn da noch alles gut ist, kannst du in der `generate_response` ein paar Log Ausgaben setzen - irgendwo innerhalb dieser paar Zeilen knallt es.

Was anderes könnte/ würde ich auch nicht machen. Was passiert denn, wenn du das error reporting komplett ausstellst?

**Comment by alexplusde** [comment]
Lag am XOutputFilter, der noch ein `<!-- XOutputFilter backend: 0 replacements in 0,0006 Sek. (from table rex_xoutputfilter) -->` angefügt hat. Das kann man in den Einstellungen deaktivieren.

~@skerbis Laufzeit, Uploadgrößen sind korrekt, es passiert wirklich schon bei kleinsten und selbst einzelnen Dateien. PHP-Version kann ich dort im Moment nicht wechseln.~

~@IngoWinter im Redaxo-System-Log befindet sich schon mal nichts.~

**Comment by Hirbod** [comment]
Doch, kann ein uploader, indem der Output Buffer vor dem response gekillt wird. ob_end_clean().. macht mein Uploader aber auch nich :D
